version: "3"

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/admin
      - ./data/web/media:/data/web/media/admin
      - ./data/web/static/admin/img:/data/web/static/admin/img

    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432