# Generated by Django 4.2.15 on 2024-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_remove_menulink_fav_icon_sitesetup_fav_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='fav_icon',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
