# Generated by Django 4.2.15 on 2024-08-26 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
